name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your desired Python version

    - name: Install dependencies from RealTimeVirtualAssistant folder
      run: |
        cd RealTimeVirtualAssitant  # Change to the correct folder
        python -m pip install --upgrade pip
        pip install .  # Install the package

    - name: Run realtime_va command
      run: |
        realtime_va  # Assuming this command needs to run in the context of the installed package

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://git-actuon-bucket --delete
